FROM quay.io/debezium/kafka:2.4

COPY DNA_files/watcher/source/get-pip.py  .
COPY DNA_files/watcher/source/requirements.txt  .
# не работает тут 
#CMD  python get-pip.py
# sudo docker exec -it watcher  python get-pip.py
