FROM quay.io/debezium/kafka:2.4

COPY api_docker/watcher/get-pip.py  .
COPY api_docker/watcher/requirements.txt  .
# не работает тут 
#CMD  python get-pip.py
# sudo docker exec -it watcher  python get-pip.py
